### PR TITLE
Move debug toggle out of Credentials (fixes #17)

### LINKED ISSUE #17: Debug should not be a field of Credentials
This https://github.com/phrase/phraseapp-go/blob/master/phraseapp/client.go#L33 feels very wrong. If anything, it should be a field here: https://github.com/phrase/phraseapp-go/blob/master/phraseapp/config.go#L12

### PR DESCRIPTION
**Pull request by alexanderwilling**
This PR moves the debug toggle into the `Client` struct so it is nicely scoped.

### CODE REVIEW

File: phraseapp/config_test.go [hunk 1]
```diff
@@ -202,7 +202,7 @@ func TestConfigPath_ConfigFromEnvButNotExisting(t *testing.T) {
 		t.Fatalf("expect an error, got none")
 	}
 
-	expErr := `file "phraseapp_does_not_exist.yml" (given in PHRASEAPP_CONFIG) doesn't exist`
+	expErr := `file "phraseapp_does_not_exist.yml" (from PHRASEAPP_CONFIG environment variable) doesn't exist`
```
Comment (tobstarr) [inline phraseapp/config_test.go:205]: this is certainly defined somewhere else (not sure where) but I guess it would sound better if it says `from the PHRASEAPP_CONFIG environment variable`.
